version: '3'
services:
  front:
    container_name: front
    hostname: front
    build:
      context: ./front
      dockerfile: ./Dockerfile
    volumes:
      - ./front:/dondon
    ports:
      - "80:3000"
    tty: true